_display = (findDisplay 15082018);
_mapCtrl =_display displayCtrl 1200;
_selectVehText = _display displayCtrl 1101; //STR_MRH_MRHInsertionHandler_selectInsertVeh
_selectVehCombo = _display displayCtrl 2100;
_AltitudeText = _display displayCtrl 1103; //STR_MRH_MRHInsertionHandler_DesiredAltIntel
_altitudeEnterEdit = _display displayCtrl 1000;
_startInsertButton = _display displayCtrl 1600;
_insertionCheckList = _display displayCtrl 1104;
_selectInsertionTypeCombo = _display displayCtrl 2101;
_selectGroupCombo = _display displayCtrl 2102;
_canAddListBox =_display displayCtrl 1500;
_onBoardListBox =_display displayCtrl 1501;
_addToPersButton = _display displayCtrl 1601;
_removeFromPersButton = _display displayCtrl 1602;
_extraGearExplanation = _display displayCtrl 1111;
_availableGearList = _display displayCtrl 1502;
_onBoardGear = _display displayCtrl 1503;
_addToGearButton = _display displayCtrl 1603;
_removeGearButton = _display displayCtrl 1604;